version: "3.4"

services:
  entity-extractor-xlu:
    image: intellidockers/entity-extractor-xlu:2.0
    container_name: intellidockers_entity-extractor-xlu
    ports:
      - "9090:8989"
    environment:
      - PROCESSES=1
      - THREADS=2
      - LICENSE=ADD_YOUR_LICENSE_KEY
    networks:
        appnet:
            ipv4_address: 10.0.0.101
networks:
    appnet:
        driver: nat
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/24"