version: "3.4"

services:
  atos_sarasvati:
    image: mdomocos/sarasvati:latest
    container_name: atos_sarasvati
    ports:
      - "8200:8200"
    environment:
      - LICENSE=ADD_YOUR_LICENSE_KEY
    networks:
        appnet:
            ipv4_address: 10.0.0.10
networks:
    appnet:
        driver: nat
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/24"