version: "3.4"

services:
  stt-ukr:
    image: intellidockers/stt-ukr:latest
    container_name: intellidockers_stt-ukr
    ports:
      - "8989:8989"
    environment:
      - PROCESSES=1
      - THREADS=2
      - APP_LANG=ua
      - LICENSE=ADD_YOUR_LICENSE_KEY
    networks:
        appnet:
            ipv4_address: 10.0.0.100
networks:
    appnet:
        driver: nat
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/24"